services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb-standalone
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./logs:/var/log/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    command: mongod --auth --bind_ip_all